# Generated by Django 3.2 on 2022-01-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
