# Generated by Django 3.2 on 2022-01-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_image_url_product_img_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Wine',
        ),
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name_plural': 'Bodies'},
        ),
        migrations.AlterModelOptions(
            name='countrystate',
            options={'verbose_name_plural': 'Countries States'},
        ),
        migrations.AlterModelOptions(
            name='winetype',
            options={'verbose_name_plural': 'Wine Types'},
        ),
    ]
